delete from t_global_sql_variables;
INSERT INTO  `t_global_sql_variables` (`id`, `name`, `content`, `function_name`, `mysql_function`, `postgres_function`, `hive_function`, `hbase_function`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`) VALUES ('1', '时间戳转化为分钟', '时间戳转换为时分(HH:mm)', 'date_format', 'FROM_UNIXTIME(@, \"%H:%i\")', 'to_char(@,\'hh:MM\')', '', '', '0', '2020-01-09 15:44:05', '2020-01-09 15:44:08', '', '', b'01');
INSERT INTO  `t_global_sql_variables` (`id`, `name`, `content`, `function_name`, `mysql_function`, `postgres_function`, `hive_function`, `hbase_function`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`) VALUES ('2', 'float数据格式化', 'float格式化，保留两位小微', 'double_format', 'CAST(@ AS DECIMAL(20,2))', '', '', '', '0', '2020-01-09 15:46:11', '2020-01-09 15:46:14', '', '', b'01');
INSERT INTO  `t_global_sql_variables` (`id`, `name`, `content`, `function_name`, `mysql_function`, `postgres_function`, `hive_function`, `hbase_function`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`) VALUES ('3', '时间格式化为年月日', '时间格式化为年月日 yyyy-mm-dd', 'date_format_date', 'DATE_FORMAT(@, \"%Y-%m-%d\")', 'to_char(@, \'YYYY-MM-DD\')', '', '', '0', '2020-01-09 16:00:18', '2020-01-09 16:00:20', '', '', b'00');
INSERT INTO  `t_global_sql_variables` (`id`, `name`, `content`, `function_name`, `mysql_function`, `postgres_function`, `hive_function`, `hbase_function`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`) VALUES ('4', '获取10天的当前时间', '获取当前时间的10天前时间 ', 'date_sub_10', 'DATE_SUB(@, INTERVAL 10 DAY)', '@ - INTERVAL \'10 DAY\' ', '', '', '0', '2020-01-09 16:03:57', '2020-01-09 16:04:00', '', '', b'00');
INSERT INTO  `t_global_sql_variables` (`id`, `name`, `content`, `function_name`, `mysql_function`, `postgres_function`, `hive_function`, `hbase_function`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`) VALUES ('5', '格式化时间为 yyyy-MM-dd HH:mm:ss', '格式化时间为 yyyy-MM-dd HH:mm:ss', 'date_format_date_time', 'DATE_FORMAT(@, \"%Y-%m-%d %H:%i:%s\")', 'to_char(@,\'yyyy-MM-dd hh:MM:ss\')', '', '', '0', '2020-01-09 20:03:33', '2020-01-09 20:03:39', '', '', b'00');
INSERT INTO  `t_global_sql_variables` (`id`, `name`, `content`, `function_name`, `mysql_function`, `postgres_function`, `hive_function`, `hbase_function`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`) VALUES ('6', '时间戳转化为 年月日 时分秒', '时间戳转化为 年月日 时分秒', 'unixtime_format_date_time', 'FROM_UNIXTIME(@, \"%Y-%m-%d %H:%i:%s\")', 'to_char(@,\'yyyy-MM-dd hh:MM:ss\')', '', '', '0', '2020-01-12 17:53:34', '2020-01-12 17:53:37', '', '', b'00');
INSERT INTO  `t_global_sql_variables` (`id`, `name`, `content`, `function_name`, `mysql_function`, `postgres_function`, `hive_function`, `hbase_function`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`) VALUES ('7', '判断是否为空', '判断是否为空，如果不为空返回第一个参数，为空返回第二个参数', 'ifnull', 'IFNULL', 'COALESCE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);




delete from `t_task_detail` where id='102';
delete from `t_task_detail` where id='103';
delete from `t_task_detail` where id='105';
delete from `t_task_detail` where id='109';
delete from `t_task_detail` where id='110';
delete from `t_task_detail` where id='112';
delete from `t_task_detail` where id='116';




INSERT INTO `t_task_detail` (`id`, `subject_id`, `task_id`, `datasource_id`, `name`, `corn`, `exec_sql`, `content`, `task_type`, `schema_name`, `depend_task_id`, `source_table_name`, `source_source_id`, `target_table`, `target_source_id`, `cancel_exec`, `source_data_type`, `target_data_type`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`, `hold_timeout`, `where_and`) VALUES ('102', '1', '1', NULL, '注册会员与实名人数', '0 1,6,11,16,21,26,31,36,41,46,51,56 * * * ? ', 'SELECT\r\n	\'\' AS area,\r\n	tt.create_time AS date,\r\n	ttt.count AS pople,\r\n	tt.count AS rate\r\nFROM\r\n	(\r\n		SELECT\r\n			create_time,\r\n			count(1) count\r\n		FROM\r\n			(\r\n				SELECT\r\n					&{date_format_date(@create_time)} AS create_time\r\n				FROM\r\n					customer_info\r\n				WHERE\r\n					create_time >= &{date_sub_10(NOW())}\r\n				AND id_card IS NOT NULL\r\n				ORDER BY\r\n					&{date_format_date(@create_time)} ASC\r\n			) t\r\n		GROUP BY\r\n			create_time\r\n	) tt\r\nJOIN (\r\n	SELECT\r\n		create_time,\r\n		count(1) count\r\n	FROM\r\n		(\r\n			SELECT\r\n				&{date_format_date(@create_time)} AS create_time\r\n			FROM\r\n				customer_info\r\n			WHERE\r\n				create_time >= &{date_sub_10(NOW())}\r\n			ORDER BY\r\n				&{date_format_date(@create_time)} ASC\r\n		) tt\r\n	GROUP BY\r\n		create_time\r\n) ttt ON tt.create_time = ttt.create_time order by date asc ', '每分钟 1 ， 6 开始执行 注册会员与实名人数', '4', '', '0', '', NULL, 'gddata_vip_regist_and_certification', NULL, '1', '1', '3', '1', '2020-02-01 08:43:14', '2020-02-01 08:43:16', '', '', b'01', NULL, '');
INSERT INTO `t_task_detail` (`id`, `subject_id`, `task_id`, `datasource_id`, `name`, `corn`, `exec_sql`, `content`, `task_type`, `schema_name`, `depend_task_id`, `source_table_name`, `source_source_id`, `target_table`, `target_source_id`, `cancel_exec`, `source_data_type`, `target_data_type`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`, `hold_timeout`, `where_and`) VALUES ('103', '1', '1', NULL, '区县工会劳模分布', '0 1,6,11,16,21,26,31,36,41,46,51,56 * * * ? ', 'SELECT\r\n	out_table_1.name as stree ,\r\n	\'成都市\' as area,\r\n	shijlmrs,\r\n	shengjlmrs,\r\n	gjlmrs\r\nFROM\r\n	(\r\n		SELECT\r\n			t_district.name AS name,\r\n			count(1) shijlmrs\r\n		FROM\r\n			model_worker_info\r\n		JOIN t_district ON address LIKE CONCAT(\'%\', t_district.name, \'%\') and  t_district.name != \'成都市\'\r\n		WHERE\r\n			hornor LIKE \'%成都市%\'\r\n		GROUP BY\r\n			t_district.name\r\n	) out_table_1\r\nJOIN (\r\n	SELECT\r\n		t_district.name AS name,\r\n		count(1) shengjlmrs\r\n	FROM\r\n		model_worker_info\r\n	JOIN t_district ON address LIKE CONCAT(\'%\', t_district.name, \'%\') and  t_district.name != \'成都市\'\r\n	WHERE\r\n		hornor LIKE \'%四川省%\'\r\n	GROUP BY\r\n		t_district.name\r\n) out_table_2 ON out_table_2.name = out_table_1.name\r\nJOIN (\r\n	SELECT\r\n		t_district.name AS name,\r\n		count(1) gjlmrs\r\n	FROM\r\n		model_worker_info\r\n	JOIN t_district ON address LIKE CONCAT(\'%\', t_district.name, \'%\') and  t_district.name != \'成都市\'\r\n	WHERE\r\n		hornor LIKE \'%国%\'\r\n	GROUP BY\r\n		t_district.name\r\n) out_table_3 ON out_table_3.name = out_table_1.name', '区县工会劳模分布， 每分钟 1 ， 6 开始执行', '4', '', '0', '', NULL, 'gddata_nmgj_distribution', NULL, '1', '1', '3', '1', '2020-01-09 17:45:38', '2020-01-09 17:45:38', '', '', b'01', NULL, '');
INSERT INTO `t_task_detail` (`id`, `subject_id`, `task_id`, `datasource_id`, `name`, `corn`, `exec_sql`, `content`, `task_type`, `schema_name`, `depend_task_id`, `source_table_name`, `source_source_id`, `target_table`, `target_source_id`, `cancel_exec`, `source_data_type`, `target_data_type`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`, `hold_timeout`, `where_and`) VALUES ('105', '1', '1', NULL, '工会大屏，实时数据-6个card', '0 1,6,11,16,21,26,31,36,41,46,51,56 * * * ? ', 'select \r\n(select count(1) as memberSum from customer_info) as qsghzchy ,\r\n(select count(1) AS count from admin_organization) as qszzs,\r\n(select count(1) as workerCount  from model_worker_info) as nmhys,\r\n \'3526\' as cyghzchys,\r\n(select count(1)  from customer_info where create_time >= &{date_format_date(now())} ) as jrzchys,\r\n(select  number as createTime  from t_online_member_count ORDER BY _CREATE_TIME_ DESC limit 1) as zxhys,\r\n\'成都市\' as area \r\nfrom DUAL', '工会大屏，实时数据-6个card', '4', '', '0', '', NULL, 'ghdata_real_time_data', NULL, '1', '1', '3', '1', '2020-02-04 15:03:44', '2020-02-04 15:03:46', '', '', b'00', '36', '');
INSERT INTO `t_task_detail` (`id`, `subject_id`, `task_id`, `datasource_id`, `name`, `corn`, `exec_sql`, `content`, `task_type`, `schema_name`, `depend_task_id`, `source_table_name`, `source_source_id`, `target_table`, `target_source_id`, `cancel_exec`, `source_data_type`, `target_data_type`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`, `hold_timeout`, `where_and`) VALUES ('109', '1', '1', NULL, '新增注册会员数', '0 1,6,11,16,21,26,31,36,41,46,51,56 * * * ? ', 'SELECT\r\n \'\' as area,\r\n	create_time  as date,\r\n	count(1) as pople_number\r\nFROM\r\n	(\r\n		SELECT\r\n			&{date_format_date(@create_time)} AS create_time,\r\n			labor_union_id labor_union_id\r\n		FROM\r\n			customer_info\r\n		WHERE\r\n			create_time >= &{date_sub_10(NOW())}\r\n	) b\r\nGROUP BY\r\n	create_time\r\nORDER BY\r\n	create_time ASC', '新增注册会员数， 每分钟 1 ， 6 开始执行', '4', '', '0', '', NULL, 'ghdata_regist_vip_datas', NULL, '1', '1', '3', '1', '2020-01-09 16:07:50', '2020-01-09 16:07:48', '', '', b'01', NULL, '');
INSERT INTO `t_task_detail` (`id`, `subject_id`, `task_id`, `datasource_id`, `name`, `corn`, `exec_sql`, `content`, `task_type`, `schema_name`, `depend_task_id`, `source_table_name`, `source_source_id`, `target_table`, `target_source_id`, `cancel_exec`, `source_data_type`, `target_data_type`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`, `hold_timeout`, `where_and`) VALUES ('110', '1', '1', NULL, '区县工会消费数据', '0 1,6,11,16,21,26,31,36,41,46,51,56 * * * ? ', 'SELECT\r\n	DISTINCT stree,online,offine, area\r\nFROM\r\n	(\r\n		SELECT\r\n			&{ifnull(\r\n				out_tabale_1.pay_time,\r\n				out_table_2.pay_time\r\n			)} AS stree,\r\n			&{ifnull(out_tabale_1.cpCount, 0)} AS online,\r\n			&{ifnull(out_table_2.cpCount, 0)} AS offine,\'成都市\' as area\r\n		FROM\r\n			(\r\n				SELECT\r\n					&{date_format_date(@pay_time)} AS pay_time,\r\n					sum(amount) / 100 cpCount\r\n				FROM\r\n					pay_cashier_orders\r\n				WHERE\r\n					state = 2\r\n				AND pay_time IS NOT NULL\r\n				GROUP BY\r\n					&{date_format_date(@pay_time)}\r\n			) out_tabale_1\r\n		LEFT JOIN (\r\n			SELECT\r\n				&{date_format_date(@pay_time)} AS pay_time,\r\n				sum(total_money) / 100 cpCount\r\n			FROM\r\n				order_item\r\n			WHERE\r\n				(\r\n					order_status = 4\r\n					OR order_status = 7\r\n				)\r\n			GROUP BY\r\n				&{date_format_date(@pay_time)}\r\n		) out_table_2 ON out_table_2.pay_time = out_tabale_1.pay_time\r\n	) out_table_1_1\r\nUNION\r\n	(\r\n		SELECT\r\n			&{ifnull(\r\n				out_tabale_1.pay_time,\r\n				out_table_2.pay_time\r\n			)} AS stree,\r\n			&{ifnull(out_tabale_1.cpCount, 0)} AS online,\r\n			&{ifnull(out_table_2.cpCount, 0)} AS offine,\'成都市\' as area\r\n		FROM\r\n			(\r\n				SELECT\r\n					&{date_format_date(@pay_time)} AS pay_time,\r\n					sum(amount) / 100 cpCount\r\n				FROM\r\n					pay_cashier_orders\r\n				WHERE\r\n					state = 2\r\n				AND pay_time IS NOT NULL\r\n				GROUP BY\r\n					&{date_format_date(@pay_time)}\r\n			) out_tabale_1\r\n		RIGHT JOIN (\r\n			SELECT\r\n				&{date_format_date(@pay_time)} AS pay_time,\r\n				sum(total_money) / 100 cpCount\r\n			FROM\r\n				order_item\r\n			WHERE\r\n				(\r\n					order_status = 4\r\n					OR order_status = 7\r\n				)\r\n			GROUP BY\r\n				&{date_format_date(@pay_time)}\r\n		) out_table_2 ON out_table_2.pay_time = out_tabale_1.pay_time\r\n	) \r\nORDER BY stree desc', '区县工会消费数据， 每分钟 1 ， 6 开始执行', '4', '', '0', '', NULL, 'ghdata_qxghxf_datas', NULL, '1', '1', '3', '1', '2020-01-09 18:22:57', '2020-01-09 18:22:57', '', '', b'01', '36', '');
INSERT INTO `t_task_detail` (`id`, `subject_id`, `task_id`, `datasource_id`, `name`, `corn`, `exec_sql`, `content`, `task_type`, `schema_name`, `depend_task_id`, `source_table_name`, `source_source_id`, `target_table`, `target_source_id`, `cancel_exec`, `source_data_type`, `target_data_type`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`, `hold_timeout`, `where_and`) VALUES ('112', '1', '1', NULL, '工会数据大屏-实时数据', '0 1,6,11,16,21,26,31,36,41,46,51,56 * * * ? ', 'select \r\n(select count(1) as memberSum from customer_info) as qsghzchy ,\r\n(select count(1) as workerCount  from model_worker_info) as nmhys,\r\n(select count(id_card) as count from customer_info where id_card is not null) smrzhys,\r\n(select  number as createTime  from t_online_member_count ORDER BY \"_CREATE_TIME_\" DESC limit 1) as zxhys,\r\n\'成都市\' as area ', '工会数据大屏-实时数据， 每分钟 1 ， 6 开始执行', '4', '', '0', '', NULL, 'ghdata_data_huizong', NULL, '1', '1', '3', '1', '2020-01-09 18:30:30', '2020-01-09 18:30:30', '', '', b'00', '36', '');
INSERT INTO `t_task_detail` (`id`, `subject_id`, `task_id`, `datasource_id`, `name`, `corn`, `exec_sql`, `content`, `task_type`, `schema_name`, `depend_task_id`, `source_table_name`, `source_source_id`, `target_table`, `target_source_id`, `cancel_exec`, `source_data_type`, `target_data_type`, `status`, `create_time`, `update_time`, `create_user`, `update_user`, `flag`, `hold_timeout`, `where_and`) VALUES ('116', '1', '1', NULL, '职工技能大赛类型分布', '0 1,6,11,16,21,26,31,36,41,46,51,56 * * * ? ', 'SELECT\r\n	skill_type,\r\n	sum(rate) AS rate\r\nFROM\r\n	(\r\n		SELECT\r\n			&{ifnull(\r\n				table1.type_work_name,\r\n				\'其他\'\r\n			)} AS skill_type,\r\n			&{ifnull(table1.cout, table2.cout)} AS rate\r\n		FROM\r\n			(\r\n				SELECT\r\n					type_work_name,\r\n					cout\r\n				FROM\r\n					(\r\n						SELECT\r\n							type_work_name,\r\n							count(1) AS cout\r\n						FROM\r\n							skills_match\r\n						WHERE\r\n							type_work_name IS NOT NULL\r\n						GROUP BY\r\n							type_work_name\r\n					) b\r\n				ORDER BY\r\n					cout DESC\r\n				LIMIT 8\r\n			) table1\r\n		RIGHT JOIN (\r\n			SELECT\r\n				type_work_name,\r\n				count(1) AS cout\r\n			FROM\r\n				skills_match\r\n			WHERE\r\n				type_work_name IS NOT NULL\r\n			GROUP BY\r\n				type_work_name\r\n		) table2 ON table2.type_work_name = table1.type_work_name\r\n	) out_table\r\nGROUP BY\r\n	skill_type', '职工技能大赛类型分布， 每分钟 1 ， 6 开始执行', '4', '', '0', '', NULL, 'ghdata_skill_game_type', NULL, '1', '1', '3', '1', '2020-01-09 16:40:14', '2020-01-09 16:40:14', '', '', b'01', NULL, '');

